#include "stm32f10x.h"

unsigned int ccr=100, sur =10, adc;
float voltaj = 10;
int i, hiz=0;
int HA, HB, HC;

void sensor(){
	if(GPIOA->IDR & 1<<10)
{ HA=1;
}else
{HA=0;
}if(GPIOA->IDR & 1<<8){HB=1;
} else { HB=0;
} if(GPIOA->IDR & 1<<15){ HC=1; 
} else { HC=0;
}}

	
void durum1(){
GPIOA->ODR &= ~ GPIO_ODR_ODR6; // 101
GPIOB->ODR &= ~ GPIO_ODR_ODR4;
GPIOA->CRL &= ~ GPIO_CRL_MODE6_0;
GPIOB->CRL &= ~ GPIO_CRL_MODE4_0;
GPIOC->CRL |= GPIO_CRL_MODE6_0;
GPIOC->ODR |= GPIO_ODR_ODR6;
GPIOB->CRL |= GPIO_CRL_MODE6_0;
GPIOB->ODR &= ~ GPIO_ODR_ODR6;

GPIOA->CRL |= GPIO_CRL_MODE6_1 ;
GPIOB->CRL &= ~ GPIO_CRL_MODE4_1 ;
GPIOC->CRL &= ~ GPIO_CRL_MODE6_1 ;
GPIOB->CRL |= GPIO_CRL_MODE0_1 ;
GPIOB->CRL &= ~ GPIO_CRL_MODE6_1 ;
GPIOC->CRL &= ~ GPIO_CRH_MODE8_1 ;}

void durum2(){
GPIOA->ODR &= ~ GPIO_ODR_ODR6; //100
GPIOB->ODR &= ~ GPIO_ODR_ODR4;
GPIOA->CRL &= ~ GPIO_CRL_MODE6_0;
GPIOB->CRL &= ~ GPIO_CRL_MODE4_0;
GPIOC->CRL |= GPIO_CRL_MODE6_0;
GPIOC->ODR |= GPIO_ODR_ODR6;
GPIOB->CRL &= ~ GPIO_CRL_MODE6_0;
GPIOA->CRL &= ~ GPIO_CRL_MODE6_1 ;
GPIOB->CRL |= GPIO_CRL_MODE4_1 ;
GPIOC->CRL &= ~ GPIO_CRL_MODE6_1 ;
GPIOB->CRL &= ~ GPIO_CRL_MODE0_1 ;
GPIOB->CRL |= GPIO_CRL_MODE6_1 ;
GPIOC->CRL &= ~ GPIO_CRH_MODE8_1 ;}

void durum3(){
GPIOC->ODR &= ~ GPIO_ODR_ODR6; // 110
GPIOB->ODR &= ~ GPIO_ODR_ODR4;
GPIOA->CRL |= GPIO_CRL_MODE6_0;
GPIOB->CRL &= ~ GPIO_CRL_MODE4_0;
GPIOC->CRL &= ~ GPIO_CRL_MODE6_0;
GPIOA->ODR |= GPIO_ODR_ODR6;
GPIOB->CRL &= ~ GPIO_CRL_MODE6_0;
GPIOA->CRL &= ~ GPIO_CRL_MODE6_1 ;
GPIOB->CRL |= GPIO_CRL_MODE4_1 ;
GPIOC->CRL &= ~ GPIO_CRL_MODE6_1 ;
GPIOB->CRL &= ~ GPIO_CRL_MODE0_1 ;
GPIOB->CRL |= GPIO_CRL_MODE6_1 ;
GPIOC->CRL &= ~ GPIO_CRH_MODE8_1 ;}

void durum4(){
GPIOC->ODR &= ~ GPIO_ODR_ODR6; //010
GPIOB->ODR &= ~ GPIO_ODR_ODR4;
GPIOA->CRL |= GPIO_CRL_MODE6_0;
GPIOB->CRL &= ~ GPIO_CRL_MODE4_0;
GPIOC->CRL &= ~ GPIO_CRL_MODE6_0;
GPIOA->ODR |= GPIO_ODR_ODR6;
GPIOB->CRL |= GPIO_CRL_MODE6_0;
GPIOB->ODR &= ~ GPIO_ODR_ODR6;

GPIOA->CRL &= ~ GPIO_CRL_MODE6_1 ;
GPIOB->CRL &= ~ GPIO_CRL_MODE4_1 ;
GPIOC->CRL |= GPIO_CRL_MODE6_1 ; 
GPIOB->CRL &= ~ GPIO_CRL_MODE0_1 ;
GPIOB->CRL &= ~ GPIO_CRL_MODE6_1 ;
GPIOC->CRL |= GPIO_CRH_MODE8_1 ;}

void durum5(){
GPIOC->ODR &= ~ GPIO_ODR_ODR6; //011
GPIOA->ODR &= ~ GPIO_ODR_ODR6;
GPIOA->CRL &= ~ GPIO_CRL_MODE6_0;
GPIOB->CRL |= GPIO_CRL_MODE4_0;
GPIOC->CRL &= ~ GPIO_CRL_MODE6_0;
GPIOB->ODR |= GPIO_ODR_ODR4;
GPIOB->CRL |= GPIO_CRL_MODE6_0;
GPIOB->ODR &= ~ GPIO_ODR_ODR6;

GPIOA->CRL &= ~ GPIO_CRL_MODE6_1 ;
GPIOB->CRL &= ~ GPIO_CRL_MODE4_1 ;
GPIOC->CRL |= GPIO_CRL_MODE6_1 ; 
GPIOB->CRL &= ~ GPIO_CRL_MODE0_1 ;
GPIOB->CRL &= ~ GPIO_CRL_MODE6_1 ;
GPIOC->CRL |= GPIO_CRH_MODE8_1 ;}

void durum6(){
GPIOC->ODR &= ~ GPIO_ODR_ODR6; //001
GPIOA->ODR &= ~ GPIO_ODR_ODR6;
GPIOA->CRL &= ~ GPIO_CRL_MODE6_0;
GPIOB->CRL |= GPIO_CRL_MODE4_0;
GPIOC->CRL &= ~ GPIO_CRL_MODE6_0;
GPIOB->ODR |= GPIO_ODR_ODR4;
GPIOB->CRL |= GPIO_CRL_MODE6_0;
GPIOB->ODR &= ~ GPIO_ODR_ODR6;

GPIOA->CRL |= GPIO_CRL_MODE6_1 ;
GPIOB->CRL &= ~ GPIO_CRL_MODE4_1 ;
GPIOC->CRL &= ~ GPIO_CRL_MODE6_1 ;
GPIOB->CRL |= GPIO_CRL_MODE0_1 ;
GPIOB->CRL &= ~ GPIO_CRL_MODE6_1 ;
GPIOC->CRL &= ~ GPIO_CRH_MODE8_1 ;	
}
void TIM3_IRQHandler(){
TIM3->SR &= ~TIM_SR_UIF;
adc=ADC1->DR;
voltaj = (adc/4); //5K pot için
if(sur<voltaj)
{
sur= sur+1;
ccr=sur;
}
else
{sur=voltaj;
}	TIM4->CCR1 &= ~TIM_PSC_PSC;
TIM4->CCR1 |= ccr;
TIM3->CCR1 &= ~TIM_PSC_PSC;
TIM3->CCR1 |= ccr;
TIM3->CCR3 &= ~TIM_PSC_PSC;
TIM3->CCR3 |= ccr;
}
void EXTI2_IRQHandler()
{
EXTI->PR |= EXTI_PR_PR2;
while(ccr>10)
{
sur=sur-1;
ccr=sur;
voltaj=sur;
sensor();
if(HA==1 && HB==0 && HC==1) // 6 durum
{durum1();
}
if(HA==1 && HB==0 && HC==0)
{durum2();
}
if(HA==1 && HB==1 && HC==0)
{durum3();
}
if(HA==0 && HB==1 && HC==0)
{durum4();
}
if(HA==0 && HB==1 && HC==1)
{durum5();
}
if(HA==0 && HB==0 && HC==1)
{durum6();
}}}
void EXTI9_5_IRQHandler(){
EXTI->PR |= EXTI_PR_PR8;
sensor();
if(HA==1 && HB==0 && HC==1) // 6 durum
{durum1();
}if(HA==1 && HB==0 && HC==0)
{durum2();
}if(HA==1 && HB==1 && HC==0)
{durum3();
}if(HA==0 && HB==1 && HC==0)
{durum4();
}if(HA==0 && HB==1 && HC==1)
{durum5();
}if(HA==0 && HB==0 && HC==1)
{durum6();
}}
void EXTI15_10_IRQHandler(){
EXTI->PR |= EXTI_PR_PR10 | EXTI_PR_PR15;
GPIOB->CRL |= GPIO_CRL_MODE6_0;
GPIOB->CRL |= GPIO_CRL_MODE4_0;
GPIOB->CRL |= GPIO_CRL_MODE0_0;
GPIOB->ODR &= ~ GPIO_ODR_ODR4;
GPIOB->ODR &= ~ GPIO_ODR_ODR0;
GPIOB->ODR &= ~ GPIO_ODR_ODR6;
GPIOB->CRL &= ~ GPIO_CRL_MODE6_0;
GPIOB->CRL &= ~ GPIO_CRL_MODE4_0;
GPIOB->CRL &= ~ GPIO_CRL_MODE0_0;
	
sensor();
{

if(HA==1 && HB==0 && HC==1) // 6 durum
{durum1();
}
if(HA==1 && HB==0 && HC==0)
{durum2();
}
if(HA==1 && HB==1 && HC==0)
{durum3();
}
if(HA==0 && HB==1 && HC==0)
{durum4();
}
if(HA==0 && HB==1 && HC==1)
{durum5();
}
if(HA==0 && HB==0 && HC==1)
{durum6();
}}}
int main(){

RCC->AHBENR |= RCC_AHBENR_CRCEN;

GPIOA->CRL |= GPIO_CRL_MODE6_1; //PA6 PWM A+
GPIOB->CRL |= GPIO_CRL_MODE5_1;
GPIOB->CRL |= GPIO_CRL_MODE0_1;// PB0 PWM A-
GPIOB->CRL |= GPIO_CRL_MODE1_1;
GPIOA->CRL |= GPIO_CRL_MODE7_1;
GPIOB->CRL |= GPIO_CRL_MODE6_1; //PB6 PWM B-
GPIOB->CRL |= GPIO_CRL_MODE7_1;
GPIOC->CRL |= GPIO_CRL_MODE6_1; //PC6 PWM C+
GPIOB->CRL |= GPIO_CRL_MODE4_1; //PB4 PWM B+
GPIOC->CRL |= GPIO_CRH_MODE9_1;
GPIOC->CRL |= GPIO_CRH_MODE8_1; // PC8 PWM C-
	
RCC->APB2ENR |= RCC_APB2ENR_AFIOEN ; 

AFIO->EVCR |=  AFIO_EVCR_EVOE;

AFIO->EVCR |=  AFIO_EVCR_PIN_1 | AFIO_EVCR_PIN_2;
AFIO->EVCR |=  AFIO_EVCR_PIN_0 | AFIO_EVCR_PIN_1 | AFIO_EVCR_PIN_2;

AFIO->EVCR |=  AFIO_EVCR_PORT_0;

AFIO->EVCR &=~  AFIO_EVCR_PIN_0;
AFIO->EVCR |=  AFIO_EVCR_PIN_0;
AFIO->EVCR |= AFIO_EVCR_PIN_2;
AFIO->EVCR |= AFIO_EVCR_PIN_0 | AFIO_EVCR_PIN_2;
AFIO->EVCR |=  AFIO_EVCR_PIN_1 | AFIO_EVCR_PIN_2;
AFIO->EVCR |=  AFIO_EVCR_PIN_0| AFIO_EVCR_PIN_1 | AFIO_EVCR_PIN_2;

AFIO->EVCR &=~  AFIO_EVCR_PORT_0;
AFIO->EVCR |= AFIO_EVCR_PORT_1;

AFIO->EVCR |=  AFIO_EVCR_PIN_2;
AFIO->EVCR |=  AFIO_EVCR_PIN_2 | AFIO_EVCR_PIN_1;

RCC->APB1ENR |= RCC_APB1ENR_TIM3EN; // TIM3 TIM4 ENABLE
RCC->APB1ENR |= RCC_APB1ENR_TIM2EN; // ? TIMER4 ENABLE OLUCAK 

GPIOA->CRL |= GPIO_IDR_IDR10 | GPIO_IDR_IDR8 | GPIO_IDR_IDR15 | GPIO_IDR_IDR2; //SENSOR VERILERINI ALMAK ICIN

GPIOB->CRL &= ~ GPIO_CRL_CNF4_1 ; //PORTLARI SIFIRLAMAK
GPIOA->CRL &= ~ GPIO_CRL_CNF0_0 | GPIO_CRL_CNF0_1;
GPIOA->CRL |= GPIO_CRL_CNF0_0 | GPIO_CRL_CNF0_1;

RCC->APB2ENR |= RCC_APB2ENR_ADC1EN;  //ADC BUSS PA0 ANALOG GIRIS
ADC1->CR2 |= ADC_CR2_ADON;
ADC1->CR2 |=ADC_CR2_CONT;
ADC1->CR2 |= ADC_CR2_SWSTART;
adc=ADC1->DR;

TIM3->PSC &= ~TIM_PSC_PSC;
TIM3->PSC |= 159;
TIM3->ARR &= ~TIM_PSC_PSC;
TIM3->ARR |= 1000U;
TIM3->CCR1 &= ~TIM_PSC_PSC;
TIM3->CCR1 |= ccr;
TIM3->CCR2 &= ~TIM_PSC_PSC;
TIM3->CCR2 |= ccr;
TIM3->CCR3 &= ~TIM_PSC_PSC;
TIM3->CCR3 |= ccr;
TIM3->CCR4 &= ~TIM_PSC_PSC;
TIM3->CCR4 |= ccr;
TIM3->DIER |= TIM_DIER_UIE;
TIM3->CCMR1 |= TIM_CCMR1_OC1M_2 | TIM_CCMR1_OC1M_1; //SAYMA YONU
TIM3->CCER |= TIM_CCER_CC1E | TIM_CCER_CC2E | TIM_CCER_CC3E; //ENABLE
TIM3->CCMR2 |= TIM_CCMR1_OC1M_1 | TIM_CCMR1_OC1M_2 | TIM_CCMR1_OC1M_0; 
NVIC_EnableIRQ(TIM3_IRQn); //INTERRUPT

TIM4->PSC &= ~TIM_PSC_PSC;
TIM4->PSC |= 159;
TIM4->ARR &= ~TIM_PSC_PSC;
TIM4->ARR |= 1000U;
TIM4->CCR1 &= ~TIM_PSC_PSC;
TIM4->CCR1 |= ccr;
TIM4->CCR2 &= ~TIM_PSC_PSC;
TIM4->CCR2 |= ccr;
TIM4->CCR3 &= ~TIM_PSC_PSC;
TIM4->CCR3 |= ccr;
TIM4->CCR4 &= ~TIM_PSC_PSC;
TIM4->CCR4 |= ccr;
TIM4->CCMR1 |= TIM_CCMR1_OC1M_2 | TIM_CCMR1_OC1M_1 | TIM_CCMR1_OC1M_0;
TIM4->CCER |= TIM_CCER_CC1E | TIM_CCER_CC2E | TIM_CCER_CC3E;
TIM4->CCMR2 |= TIM_CCMR1_OC1M_0 | TIM_CCMR1_OC1M_2 | TIM_CCMR1_OC1M_1;

TIM3->CR1 |= TIM_CR1_CEN;
TIM4->CR1 |= TIM_CR1_CEN;

EXTI->IMR |= EXTI_IMR_MR8  | EXTI_IMR_MR10| EXTI_IMR_MR15| EXTI_IMR_MR2; // KESME GIRISI PA8, PA10, PA15
EXTI->RTSR |= EXTI_RTSR_TR8 |  EXTI_RTSR_TR10 |  EXTI_RTSR_TR15 |  EXTI_RTSR_TR2; 
EXTI->FTSR |= EXTI_FTSR_TR8 |  EXTI_FTSR_TR10 |  EXTI_FTSR_TR15 |  EXTI_FTSR_TR2;	

NVIC_EnableIRQ(40); //10_15 ARASI INTERRUPT
NVIC_EnableIRQ(23); //5_9 ARASI INTERRUPT
NVIC_EnableIRQ(8);
NVIC_EnableIRQ(TIM3_IRQn);

while(1){

sensor();
if(HA==1 && HB==0 && HC==1) // 6 durum
{durum1();
}if(HA==1 && HB==0 && HC==0)
{durum2();
}if(HA==1 && HB==1 && HC==0)
{durum3();
}if(HA==0 && HB==1 && HC==0)
{durum4();
}if(HA==0 && HB==1 && HC==1)
{durum5();
}if(HA==0 && HB==0 && HC==1)
{durum6();
}}}

